--Describe about pagination, task by project, status
-- Pagination (DB2/H2)
SELECT * FROM TAREFA
ORDER BY DATA_CRIACAO DESC
OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY;

-- Join Task x Project
SELECT t.ID, t.TITULO, t.STATUS, t.DATA_CRIACAO, p.NOME AS PROJETO
FROM TAREFA t
JOIN PROJETO p ON p.ID = t.ID_PROJETO
ORDER BY t.DATA_CRIACAO DESC;

-- Group by STATUS
SELECT STATUS, COUNT(*) AS QTD
FROM TAREFA
GROUP BY STATUS
ORDER BY QTD DESC;
